const CACHE_KEY='steamtech_cache';let cache={};try{const c=localStorage.getItem(CACHE_KEY);if(c)cache=JSON.parse(c);}catch(e){}
const PROXIES=['https://api.allorigins.win/raw?url=','https://corsproxy.io/?url=','https://api.codetabs.com/v1/proxy?quest='];
const STATIC_DB={"1228521":"1915972288405109143","730":"8191659448416564362"};
async function fetchViaProxy(url){for(const proxy of PROXIES){try{const r=await fetch(proxy+encodeURIComponent(url),{signal:AbortSignal.timeout(8000)});if(r.ok)return await r.text();}catch(e){}}throw new Error('All proxies failed');}
function extractManifestId(html){const patterns=[/Manifest ID<\/td>\s*<td[^>]*>\s*(\d{17,20})\s*</i,/manifestid["']?\s*>\s*(\d{17,20})/i,/"manifestid":\s*"(\d{17,20})"/i,/manifest\s+id\s*[:=]\s*(\d{17,20})/i,/<td>Manifest ID<\/td>\s*<td[^>]*>(\d{17,20})<\/td>/i,/ManifestID:\s*(\d{17,20})/i,/Manifest\s+ID\s*:\s*(\d{17,20})/i];for(const p of patterns){const m=html.match(p);if(m&&m[1])return m[1];}return null;}
async function fetchManifestId(depotId){if(cache[depotId])return cache[depotId];if(STATIC_DB[depotId]){cache[depotId]=STATIC_DB[depotId];localStorage.setItem(CACHE_KEY,JSON.stringify(cache));return STATIC_DB[depotId];}const url=`https://steamdb.info/depot/${depotId}/`;let html;try{html=await fetchViaProxy(url);}catch(e){return null;}const id=extractManifestId(html);if(id){cache[depotId]=id;localStorage.setItem(CACHE_KEY,JSON.stringify(cache));return id;}return null;}
async function sha256(m){const b=new TextEncoder().encode(m);const h=await crypto.subtle.digest('SHA-256',b);const a=Array.from(new Uint8Array(h));return a.map(x=>x.toString(16).padStart(2,'0')).join('');}
async function generateLua(depotId){const t=depotId.trim();if(!t||!/^\d+$/.test(t))return null;const salt="SteamDepotKeySalt_2024";const hash=await sha256(t+salt);const key=hash.substring(0,64);return`addappid(${t})\naddappid(${t},0,"${key}")`;}
const input=document.getElementById('depotInput');const output=document.getElementById('output');const genBtn=document.getElementById('generateBtn');const copyBtn=document.getElementById('copyBtn');const downBtn=document.getElementById('downloadBtn');const statusText=document.getElementById('statusText');let lastLua=null;let lastId=null;
async function handleGenerate(){const val=input.value.trim();if(!val||!/^\d+$/.test(val)){output.innerHTML=`<div class="label">output</div><div class="empty">invalid Depot ID (digits only)</div>`;lastLua=null;lastId=null;statusText.textContent='';return;}statusText.innerHTML=`<span class="loader"></span>`;const lua=await generateLua(val);if(!lua){statusText.textContent='';return;}lastLua=lua;lastId=val;output.innerHTML=`<div class="label">${val}.lua</div><pre>${lua}</pre>`;statusText.textContent='';}
genBtn.addEventListener('click',handleGenerate);input.addEventListener('keydown',e=>{if(e.key==='Enter')handleGenerate();});
copyBtn.addEventListener('click',function(){if(!lastLua){alert('Generate first');return;}navigator.clipboard.writeText(lastLua).then(()=>{const orig=this.textContent;this.textContent='Copied!';setTimeout(()=>this.textContent=orig,1200);}).catch(()=>{const pre=output.querySelector('pre');if(pre){const r=document.createRange();r.selectNode(pre);window.getSelection().removeAllRanges();window.getSelection().addRange(r);document.execCommand('copy');alert('Copied!');}});});
downBtn.addEventListener('click',async function(){if(!lastLua){alert('Generate first');return;}const zip=new JSZip();zip.file(`${lastId}.lua`,lastLua);try{const blob=await zip.generateAsync({type:'blob'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${lastId}.zip`;document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(url);}catch(e){alert('ZIP error: '+e.message);}});
window.addEventListener('DOMContentLoaded',()=>input.focus());
